// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKIS0Nvz2zP-iHg99qnX4bACdIEQeqfRc',
    appId: '1:392990425719:web:66ded65c952d96777d3c72',
    messagingSenderId: '392990425719',
    projectId: 'newsfirebase-33061',
    authDomain: 'newsfirebase-33061.firebaseapp.com',
    storageBucket: 'newsfirebase-33061.appspot.com',
    measurementId: 'G-XP20GKL0E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3jXRCkvAj5QPEwIUHeKb1dlt0Ac6r8dU',
    appId: '1:392990425719:android:ee5afd763164cd4a7d3c72',
    messagingSenderId: '392990425719',
    projectId: 'newsfirebase-33061',
    storageBucket: 'newsfirebase-33061.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGB9STNi_QGMVOlowmlFBKFE8zctfO8Ts',
    appId: '1:392990425719:ios:5c6e725ce4071a547d3c72',
    messagingSenderId: '392990425719',
    projectId: 'newsfirebase-33061',
    storageBucket: 'newsfirebase-33061.appspot.com',
    iosBundleId: 'com.example.newsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGB9STNi_QGMVOlowmlFBKFE8zctfO8Ts',
    appId: '1:392990425719:ios:5c6e725ce4071a547d3c72',
    messagingSenderId: '392990425719',
    projectId: 'newsfirebase-33061',
    storageBucket: 'newsfirebase-33061.appspot.com',
    iosBundleId: 'com.example.newsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKIS0Nvz2zP-iHg99qnX4bACdIEQeqfRc',
    appId: '1:392990425719:web:d372c7d037e3a1877d3c72',
    messagingSenderId: '392990425719',
    projectId: 'newsfirebase-33061',
    authDomain: 'newsfirebase-33061.firebaseapp.com',
    storageBucket: 'newsfirebase-33061.appspot.com',
    measurementId: 'G-0WMF5NW31Q',
  );
}
